### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by okj203** [skowildcats/ComfortBnB#1]
- [x] A user does not belong to a review/reservation/place, so foreign key columns such as review_id, reservation_id, etc. are not necessary 
- [x] Reservations table needs checkin date and checkout date
- [x] Properties table needs address data (longitude and latitude) for Google Maps API, rather than just a location column.
- [x] In the reviews table, the review column might be renamed as `body` or `content` to avoid confusion
- [x] After updating schema, consider reflecting the changes on the sample state
- [x] In the frontend routes, what’s the difference between ReservationComponent and ReservationIndexItem?

**Comment by skowildcats** [comment]
Thanks for the review Cathy, I've made all the changes and updated the schema and sample state accordingly.

 I initially added reservationindexitem to render a separate view for when a user wants to see their past, current and upcoming reservations but then I realized that I could just redirect them to a reservationcomponent so I've fixed that as well.
